### ISSUE TITLE
WAV input/output non-functional

### ISSUE THREAD

**Issue by Rhynorater** [Skype4Py/Skype4Py#14]
Hello,

I believe I have found an error in the Skype4Py's InputDevice function in regards to WAV files. I use the following code using the Python 2.7 32bit interpreter on a 64 bit Windows 7 computer running Skype version 6.1.0.129. No wave files play, not even Microsoft WAV format, 16 signed bits per sample, 1 channel, 16KHz sample rate WAV files.

Thanks so much for your prompt attention to this subject.
Justin

import Skype4Py
import time
s=Skype4Py.Skype()
s.Attach()
c = s.PlaceCall("testingfordml")
c.InputDevice(Skype4Py.callIoDeviceTypeFile, "ans_51.wav")
time.sleep(4)
c.Finish()

**Comment by blackhatlab** [comment]
I have this too
