### ISSUE TITLE
Typo in title

### ISSUE THREAD

**Issue by abmohan** [Skype4Py/Skype4Py#31]
A small typo in the title of the Github repository: 
the word "independent" was incorrectly spelled "indepeneant" (i.e. "Platform indepeneant Python wrapper for the Skype API.", but should be "Platform-independent Python wrapper for the Skype API.")

**Comment by pwittchen** [comment]
:+1:

**Comment by davsebamse** [comment]
Thanks for the heads up. It looks like it is fixed now.
