### ISSUE TITLE
Error when marking message as read

### ISSUE THREAD

**Issue by Jake0oo0** [Skype4Py/Skype4Py#36]
Getting [this](https://gist.github.com/Jake0oo0/7526cf759d9cc5209f3c) error when marking a ChatMessage as read.

**Comment by davsebamse** [comment]
Please provide the gist again.

**Comment by Jake0oo0** [comment]
Long gone, unfortunately.

**Comment by davsebamse** [comment]
Ok. Thanks for the reply
