### ISSUE TITLE
Messages with HTML support

### ISSUE THREAD

**Issue by MartynasZilinskas** [Skype4Py/Skype4Py#46]
Linux skype client, still supports html messages.

```
<font size="32">EXAMPLE</font>
```

![1424211283](https://cloud.githubusercontent.com/assets/562658/6238369/2ba0fdd6-b703-11e4-8e2b-86a93d1194fb.png)

But you need to enter message with "CTRL+SHIFT+ENTER" (I think, I don't remember now).
So I wonder is it possible to submit message with this library?
(I remember that you could change Mood with 3rd party programs, so I am thinking that's possible to do with Skype4Py)

**Comment by Goz3rr** [comment]
I don't think it's possible through the DBUS API but one (albeit somewhat horrible) workaround is using the `OPEN CHAT [id]` command to have Skype focus that chat and then use something like xdotool to write your text and press ctrl+shift+enter

**Comment by miohtama** [comment]
Now there is Skype Web API available:

https://msdn.microsoft.com/en-us/library/office/dn962137%28v=office.16%29.aspx

I have not checked it myself, but it might do more tricks.

On 16 June 2015 at 16:04, Goz3rr <notifications@github.com> wrote:

> I don't think it's possible through the DBUS API but one (albeit somewhat
> horrible) workaround is using the OPEN CHAT [id] command to have Skype
> focus that chat and then use something like xdotool to write your text and
> press ctrl+shift+enter
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/awahlig/skype4py/issues/46#issuecomment-112598640>.
>



-- 
Mikko Ohtamaa
http://opensourcehacker.com
http://twitter.com/moo9000

**Comment by lavinachitara** [comment]
Hi,

In windows
skype.SendMessage(user.fullname, 'May I help you')

above function is not working and throwing an error as below:

raise SkypeError(int(errnum), errstr)
Skype4Py.errors.SkypeError: [Errno 508] CHAT: CREATE: opening a dialog to the given user failed
