### ISSUE TITLE
Building tutorial

### ISSUE THREAD

**Issue by GAMELASTER** [Skype4Py/Skype4Py#49]
Hey,

i have little troubles with installing... How to i install Skype4py in Debian for still work? Becouse first its writing to me is missing module DBUS, and second the true, i must every reboot reinstall the Skype4py..

thanks

**Comment by davsebamse** [comment]
You need the python-dbus and python-gobject packages as well.

**Comment by davsebamse** [comment]
And it is corrected in setup.py
