### ISSUE TITLE
Segmentation fault when attaching to skype

### ISSUE THREAD

**Issue by matclab** [Skype4Py/Skype4Py#5]
The following python script : 

``` python
import Skype4Py

skype = Skype4Py.Skype()
skype.FriendlyName = 'test_kjdfsdt'
skype.Attach()
```

Failed with a segmentation fault.

The end of the trace of  `<python -v -v scriptname>` is :

```
import Skype4Py.lang.x1 # precompiled from /usr/lib/python2.7/site-packages/Skype4Py/lang/x1.pyc
# trying /usr/lib/python2.7/encodings/utf_8.so
# trying /usr/lib/python2.7/encodings/utf_8module.so
# trying /usr/lib/python2.7/encodings/utf_8.py
# /usr/lib/python2.7/encodings/utf_8.pyc matches /usr/lib/python2.7/encodings/utf_8.py
import encodings.utf_8 # precompiled from /usr/lib/python2.7/encodings/utf_8.pyc
Erreur de segmentation
```
## Versions

skype4py 1.0.32.0
skype 4.1.0.20
OS : linux 3.6.6 x86_64
distrib : Arch linux
python : 2.7.3

**Comment by AnveshMora** [comment]
Hi Guys,

I'm not able to Attach the instance of the Skype and facing with Segmentation fault:11 error.

Facing issue with latest version.

Package    Version
---------- -------
pip        10.0.1 
setuptools 39.1.0 
Skype4Py   1.0.35 
wheel      0.31.0

Could any help me out with the solution if figured out.?
