### ISSUE TITLE
Setup.py syntax error

### ISSUE THREAD

**Issue by deathbyfreezeray** [Skype4Py/Skype4Py#60]
In the python3-beta branch, the distutils setup script is missing a parenthesis on line 111. Here is a diff of it and the corrected file. 
[setup.py.diff.txt](https://github.com/Skype4Py/Skype4Py/files/120936/setup.py.diff.txt)

**Comment by davsebamse** [comment]
Hi

Can you provide it as a pull request on the python3 branch?

Thanks for your report anyway.

**Comment by deathbyfreezeray** [comment]
I am not too familiar with github (this is my first open-source contribution), do I just fork the python3 branch, correct my copy, and then ask to merge with it in the pull request?

**Comment by miohtama** [comment]
Yep. When you fork you will get your own repository on Github. You can push changes there and then press "Pull request" button in Github web UI.

**Comment by davsebamse** [comment]
As @miohtama says:

1. Fork the project.
2. Clone the project. Use the following command ```git clone https://github.com/deathbyfreezeray/Skype4Py```
3. Checkout the correct branch: ```git checkout python3-beta```
4. Make the changes
5. Make a commit
6. Push the commit
7. Create pull request with the python3-beta branch in your repos and the python3-beta branch in the main repository
8. Wait for praise :-)

**Comment by deathbyfreezeray** [comment]
Thanks, those instructions were concise and simple. Git's well written man page helps as well. I now made my first commit to an open-source project. In the grand scheme of things, it wasn't an important one, but it is a step in the right direction. Thanks everyone!
