### ISSUE TITLE
Troubles with dbus and x11 transport 

### ISSUE THREAD

**Issue by zorar4ik** [Skype4Py/Skype4Py#72]
I am facing troubles when I run my script on these transports.
When I use dbus I receive this:
`raise SkypeAPIError('Skype attach timeout')
Skype4Py.errors.SkypeAPIError: Skype attach timeout.`
When I use x11: 
`X Error of failed request:  BadWindow (invalid Window parameter)
  Major opcode of failed request:  25 (X_SendEvent)
  Resource id in failed request:  0x300000f
  Serial number of failed request:  14
  Current serial number in output stream:  14`

It worked fine on Friday, 3 days ago with x11

**Comment by nikswap** [comment]
Which version of skype? The new version of skype is using the web edition of skype, and skype api do not work with that.
