### ISSUE TITLE
Terminated by signal SIGSEGV (Address boundary error)

### ISSUE THREAD

**Issue by lc-rezende** [Skype4Py/Skype4Py#75]
This is what is happening and I couldn't find any solution on Google. Do you have any clue?

```
Python 2.7.10 (default, Jul 30 2016, 19:40:32) 
[GCC 4.2.1 Compatible Apple LLVM 8.0.0 (clang-800.0.34)] on darwin
Type "help", "copyright", "credits" or "license" for more information.

>>> import Skype4Py
>>> skype = Skype4Py.Skype()
>>> skype.Attach()
fish: 'python' terminated by signal SIGSEGV (Address boundary error)
```

I am trying to use Skype4Py to make automatic calls from a list of phones. I am using a MacOS.

**Comment by miohtama** [comment]
In the past this has been issue when mixing 32-bit and 64-bit binaries and libraries.

**Comment by lc-rezende** [comment]
Just to let you know, what I had to do was to uninstall the version I had installed and installed again using `arch -i386 pip install Skype4Py`. After that I ran python using `arch -i386 python` and it worked fine. Thank you for the hint!
